// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxqljlrdltfkfqyhgubj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4cWxqbHJkbHRma2ZxeWhndWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDYyOTgsImV4cCI6MjA3MjQ4MjI5OH0.u6tJ3iJH0jFOo00gXIbvCnk5qbv5CZZD9szlfZCpYQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});